<?php
/**
 * Copyright © Shopreviews. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Shopreviews\Connect\Block\Adminhtml\Config\AccountInformation $block */
/** @var Magento\Framework\Escaper $escaper */

$logo = $block->getViewFileUrl('Shopreviews_Connect::images/shopreviews_logo_big.png');
$activeClass = !$block->isAccountActive() ? 'not-active' : 'active';
?>

<section class="shopreviews-account-info <?= $activeClass ?>" 
         data-mage-init='{ "Shopreviews_Connect/js/account-info": {} }'>
    <?php if(!$block->isAccountActive()): ?>
        <span   class="button-connect" 
                id="shopreviews-button-connect" 
                data-url="<?= $escaper->escapeUrl($block->getConnectUrl()); ?>">
            <span>
                <?= $escaper->escapeHtml(__('Setup Account')); ?>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" fill="currentColor">
                    <path d="M504-480 320-664l56-56 240 240-240 240-56-56 184-184Z"/>
                </svg>
            </span>
        </span>
    <?php endif; ?>

    <div class="shopreviews-account-table">
        <table>
            <?php foreach ($block->getAccountInformation() as $row): ?>
                <tr>
                    <td data-element="label">
                        <?= $escaper->escapeHtml(__($row['label'])); ?>
                    </td>
                    <td data-element="value" 
                        class="<?= $escaper->escapeHtmlAttr($row['actionId']); ?>" 
                        <?= empty($row['actionId']) ? 'colspan="2"' : '' ?>
                    >
                        <?= $escaper->escapeHtml(__($row['value'])); ?>
                    </td>
                    
                    <?php if (!empty($row['actionId'])): ?>
                        <td data-element="action" 
                            class="<?= $escaper->escapeHtmlAttr($row['actionId']); ?>"
                        >
                            <?php if($row['actionTarget'] === '_self'): ?>
                                <a  href="<?= $escaper->escapeUrl($row['actionUrl']); ?>" target="_self"
                                    id="<?= $escaper->escapeHtmlAttr(__($row['actionId'])); ?>">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" fill="currentColor">
                                        <path d="M480-160q-134 0-227-93t-93-227q0-134 93-227t227-93q69 0 132 28.5T720-690v-110h80v280H520v-80h168q-32-56-87.5-88T480-720q-100 0-170 70t-70 170q0 100 70 170t170 70q77 0 139-44t87-116h84q-28 106-114 173t-196 67Z"/>
                                    </svg>
                                </a>
                            <?php else: ?>
                                <span id="<?= $escaper->escapeHtmlAttr(__($row['actionId'])); ?>" 
                                      data-url="<?= $escaper->escapeUrl($row['actionUrl']); ?>">
                                    <?php if ($row['actionId'] === 'shopreviews-show-websites'): ?>
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" fill="currentColor">
                                            <path d="m370-80-16-128q-13-5-24.5-12T307-235l-119 50L78-375l103-78q-1-7-1-13.5v-27q0-6.5 1-13.5L78-585l110-190 119 50q11-8 23-15t24-12l16-128h220l16 128q13 5 24.5 12t22.5 15l119-50 110 190-103 78q1 7 1 13.5v27q0 6.5-2 13.5l103 78-110 190-118-50q-11 8-23 15t-24 12L590-80H370Zm70-80h79l14-106q31-8 57.5-23.5T639-327l99 41 39-68-86-65q5-14 7-29.5t2-31.5q0-16-2-31.5t-7-29.5l86-65-39-68-99 42q-22-23-48.5-38.5T533-694l-13-106h-79l-14 106q-31 8-57.5 23.5T321-633l-99-41-39 68 86 64q-5 15-7 30t-2 32q0 16 2 31t7 30l-86 65 39 68 99-42q22 23 48.5 38.5T427-266l13 106Zm42-180q58 0 99-41t41-99q0-58-41-99t-99-41q-59 0-99.5 41T342-480q0 58 40.5 99t99.5 41Zm-2-140Z"/>
                                        </svg>
                                    <?php endif; ?>

                                    <?php if ($row['actionId'] === 'shopreviews-show-sources'): ?>
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" fill="currentColor">
                                            <path d="m363-390 117-71 117 71-31-133 104-90-137-11-53-126-53 126-137 11 104 90-31 133ZM80-80v-720q0-33 23.5-56.5T160-880h640q33 0 56.5 23.5T880-800v480q0 33-23.5 56.5T800-240H240L80-80Zm126-240h594v-480H160v525l46-45Zm-46 0v-480 480Z"/>
                                        </svg>
                                    <?php endif; ?>
                                </span>
                            <?php endif; ?>
                        </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>

    <?php if ($block->isAccountActive()): ?>
        <span   class="button-disconnect" 
                id="shopreviews-button-disconnect" 
                data-url="<?= $escaper->escapeUrl($block->getDisconnectUrl()); ?>">
            <?= $escaper->escapeHtml(__('Disconnect Account')); ?>
        </span>
    <?php endif; ?>

    <!-- Modal section -->
    <?php foreach ($block->getModalInforamtion() as $info): ?>
        <div class="shopreviews-modal" id="<?= $escaper->escapeHtmlAttr($info['id']); ?>">
            <div class="shopreviews-modal-header">
                <img src="<?= $escaper->escapeUrl($logo) ?>" alt="Shopreview logo" width="220" height="44"/>
                <h2 class="shopreviews-modal-title">
                    <?= $escaper->escapeHtml($info['title']); ?>
                </h2>
            </div>
            <div class="shopreviews-modal-box">
                <iframe src=""></iframe>
            </div>
        </div>
    <?php endforeach; ?>

    <div class="shopreviews-modal-overlay"></div>
</section>
